### ISSUE TITLE
Better ISO8601 Support

### ISSUE THREAD

**Issue by geota** [fge/json-schema-validator#158] opened 2015-05-29 20:53 UTC
Python and other languages provide microsecond resolution. The default date-time format should support this.

This fails validation:
2015-05-29T15:45:42.976424Z 

This succeeds:
2015-05-29T15:45:42.976Z

If you are interested, I could code up a PR and send it.

**Comment by ajbrown** [comment] 2015-06-08 23:20
This is a duplicate of #143, fixed by #147

**Closed** 2015-06-15 15:56 UTC
